'use strict';
const text = {
skip:['Перейти к меню','Мәзірге өту','Skip to menu'],navigation:['Навигация','Навигация','Navigation'],language:['Язык','Тіл','Language'],navMenu:['Банкетное меню','Банкет мәзірі','Banquet menus'],navDishes:['Блюда','Тағамдар','Dishes'],navAbout:['Ресторан','Мейрамхана','Restaurant'],navContact:['Контакты','Байланыс','Contact'],
heroEyebrow:['АТЫРАУ · БАНКЕТНЫЙ РЕСТОРАН','АТЫРАУ · БАНКЕТ МЕЙРАМХАНАСЫ','ATYRAU · BANQUET RESTAURANT'],heroTitle:['Вкус вашего<br><em>особенного</em> дня.','Ерекше күннің<br><em>есте қалар</em> дәмі.','A taste of your<br><em>special</em> day.'],heroDescription:['Соберите близких за щедрым столом.<br>Ваши важные события — в Aspandiar.','Жақындарыңызды мол дастарханға жинаңыз.<br>Маңызды сәттеріңіз — Aspandiar-да.','Bring your loved ones to a generous table.<br>Celebrate your important moments at Aspandiar.'],chooseMenu:['Выбрать меню','Мәзірді таңдау','Explore menus'],discussBanquet:['Обсудить банкет','Банкетті талқылау','Discuss your banquet'],upTo200:['до 200','200-ге дейін','up to 200'],guestsInHall:['гостей в зале','залдағы қонақ саны','guests in the hall'],from5000:['от 5 000 ₸','5 000 ₸-ден','from 5,000 ₸'],perPerson:['на одну персону','бір адамға','per person'],kazakhstan:['Казахстан','Қазақстан','Kazakhstan'],heroPhoto:['Салат с овощами и кунжутом','Көкөніс пен күнжіт салаты','Vegetable salad with sesame'],pearPhoto:['Салат с грушей и сыром','Алмұрт пен ірімшік салаты','Pear & cheese salad'],heroCaption:['ЩЕДРЫЙ СТОЛ. ТЁПЛЫЕ ВСТРЕЧИ.','МОЛ ДАСТАРХАН. ЖЫЛЫ КЕЗДЕСУЛЕР.','A GENEROUS TABLE. A WARM WELCOME.'],occasionWedding:['Свадьбы','Үйлену тойы','Weddings'],occasionFamily:['Семейные торжества','Отбасылық мерекелер','Family celebrations'],occasionAnniversary:['Юбилеи','Мерейтойлар','Anniversaries'],
menuEyebrow:['ВАШ ПРАЗДНИК НАЧИНАЕТСЯ С МЕНЮ','МЕРЕКЕҢІЗ МӘЗІРДЕН БАСТАЛАДЫ','YOUR CELEBRATION STARTS WITH THE MENU'],menuTitle:['Четыре варианта.<br><em>Один прекрасный вечер.</em>','Төрт нұсқа.<br><em>Керемет бір кеш.</em>','Four menus.<br><em>One wonderful evening.</em>'],menuIntro:['Выберите бюджет, посмотрите блюда и сравните, что входит в каждое меню.','Бюджетіңізге сай мәзірді таңдап, тағамдар мен әр нұсқаның құрамын салыстырыңыз.','Choose your budget, explore the dishes and compare what each menu includes.'],compareMenus:['Сравнить все меню','Барлық мәзірді салыстыру','Compare all menus'],hideCompare:['Скрыть сравнение','Салыстыруды жасыру','Hide comparison'],menuTabs:['Банкетные меню','Банкет мәзірлері','Banquet menus'],banquetMenu:['БАНКЕТНОЕ МЕНЮ','БАНКЕТ МӘЗІРІ','BANQUET MENU'],discussMenu:['Обсудить это меню','Осы мәзірді талқылау','Discuss this menu'],bringTitle:['Что принести с собой','Өзіңізбен не әкелу керек','What to bring with you'],bringNote:['Количество и условия согласуйте с администрацией.','Мөлшері мен шарттарын әкімшілікпен келісіңіз.','Confirm quantities and arrangements with the team.'],originalMenu:['Открыть оригинал меню','Мәзірдің түпнұсқасын ашу','View original menu'],includedTitle:['Включено в меню','Мәзірге кіреді','Included in your menu'],positions:['позиций','позиция','items'],
photoNote:['Фото показывают варианты подачи. «Пример подачи» — иллюстрация; фотографии вариантов блюд взяты из присланных материалов. Состав, порции и доступность согласуйте с администрацией.','Суреттер ұсыну нұсқаларын көрсетеді. «Ұсыну үлгісі» — иллюстрация; тағам нұсқаларының фотолары жіберілген материалдардан алынған. Құрамы, порциясы мен қолжетімділігін әкімшілікпен келісіңіз.','Photos show serving options. “Serving example” indicates an illustration; dish option photos come from the supplied materials. Confirm ingredients, portions and availability with the team.'],estimateEyebrow:['ПЛАНИРУЙТЕ СВОЙ ВЕЧЕР','КЕШІҢІЗДІ ЖОСПАРЛАҢЫЗ','PLAN YOUR EVENING'],estimateTitle:['Сколько гостей вы приглашаете?','Қанша қонақ шақырасыз?','How many guests are you inviting?'],guestCount:['Количество гостей','Қонақ саны','Number of guests'],guestMinus:['Меньше гостей','Қонақ санын азайту','Fewer guests'],guestPlus:['Больше гостей','Қонақ санын көбейту','More guests'],guestUnit:['гостей','қонақ','guests'],estimateNote:['Ориентировочная стоимость меню','Мәзірдің болжамды құны','Estimated menu cost'],askAvailability:['Уточнить дату','Күнді нақтылау','Check your date'],estimateDisclaimer:['Расчёт: стоимость выбранного меню × количество гостей. Дополнительные услуги и окончательные условия уточняются отдельно.','Есеп: таңдалған мәзір бағасы × қонақ саны. Қосымша қызметтер мен соңғы шарттар бөлек келісіледі.','Estimate: selected menu price × number of guests. Additional services and final arrangements are agreed separately.'],
dishEyebrow:['ДЕТАЛИ, КОТОРЫЕ СОЗДАЮТ ПРАЗДНИК','МЕРЕКЕНІ АЙШЫҚТАЙТЫН ТАҒАМДАР','THE DETAILS THAT MAKE A CELEBRATION'],dishTitle:['Сначала выбирают <em>глазами.</em>','Алдымен <em>көз сүйсінеді.</em>','A feast for <em>the eyes.</em>'],dishIntro:['Знакомые вкусы и красивые подачи. Посмотрите варианты салатов и горячих блюд для вашего стола.','Таныс дәмдер мен әсем ұсынылым. Дастарханға арналған салаттар мен ыстық тағам нұсқаларын қараңыз.','Familiar flavours, beautifully served. Explore salad and main course options for your table.'],dishFilters:['Категории блюд','Тағам санаттары','Dish categories'],allDishes:['Все блюда','Барлық тағам','All dishes'],salads:['Салаты','Салаттар','Salads'],hotDishes:['Горячее','Ыстық тағамдар','Main courses'],galleryNote:['Варианты по присланным фотографиям. Доступность каждого блюда подтверждает администратор.','Жіберілген фотолар бойынша нұсқалар. Әр тағамның қолжетімділігін әкімші растайды.','Options from the supplied photos. The team confirms availability of each dish.'],filmLabel:['БАНКЕТНЫЙ СТОЛ ASPANDIAR','ASPANDIAR БАНКЕТ ДАСТАРХАНЫ','THE ASPANDIAR BANQUET TABLE'],videoLabel:['Видео сервированного стола Aspandiar','Aspandiar дастарханының бейнесі','Video of the Aspandiar banquet table'],aboutEyebrow:['МЕСТО ДЛЯ ВАШИХ ВАЖНЫХ МОМЕНТОВ','МАҢЫЗДЫ СӘТТЕРІҢІЗГЕ АРНАЛҒАН ОРЫН','A PLACE FOR YOUR IMPORTANT MOMENTS'],aboutTitle:['Традиции гостеприимства.<br><em>В кругу близких.</em>','Қонақжайлық дәстүрі.<br><em>Жақындарыңызбен бірге.</em>','A tradition of hospitality.<br><em>Surrounded by loved ones.</em>'],aboutDescription:['Aspandiar — банкетный ресторан в Атырау для встреч, которые хочется запомнить. Зал вмещает до 200 гостей, а четыре варианта меню помогают подобрать стол под ваше событие.','Aspandiar — Атыраудағы есте қалар кездесулерге арналған банкет мейрамханасы. Зал 200 қонаққа дейін қабылдайды. Төрт мәзір нұсқасы мерекеңізге сай дастархан таңдауға көмектеседі.','Aspandiar is a banquet restaurant in Atyrau for gatherings to remember. The hall welcomes up to 200 guests, with four menu packages to suit your celebration.'],aboutCapacity:['гостей — вместимость зала','қонақ — зал сыйымдылығы','guests — hall capacity'],aboutMenus:['варианта банкетного меню','банкет мәзірінің нұсқасы','banquet menu packages'],planEvent:['Спланировать торжество','Мерекені жоспарлау','Plan your celebration'],
faqEyebrow:['ПЕРЕД БРОНИРОВАНИЕМ','БРОНДАУ АЛДЫНДА','BEFORE YOU BOOK'],faqTitle:['Позаботимся <em>о деталях.</em>','Әр бөлшек <em>назарда.</em>','Every detail <em>considered.</em>'],contactEyebrow:['ДО ВСТРЕЧИ В ASPANDIAR','ASPANDIAR-ДА КЕЗДЕСКЕНШЕ','SEE YOU AT ASPANDIAR'],contactTitle:['Ваш праздник<br><em>начинается здесь.</em>','Мерекеңіз<br><em>осы жерден басталады.</em>','Your celebration<br><em>starts here.</em>'],administration:['Администрация ресторана','Мейрамхана әкімшілігі','Restaurant administration'],writeWhatsApp:['Написать в WhatsApp','WhatsApp-қа жазу','Message on WhatsApp'],call:['Позвонить','Қоңырау шалу','Call us'],address:['Атырау, ул. Шукыр Еркинов, 77а','Атырау, Шүкір Еркінов көшесі, 77а','77a Shukyr Yerkinov Street, Atyrau'],district:['Микрорайон Привокзальный-3, Казахстан','Привокзальный-3 шағын ауданы, Қазақстан','Privokzalny-3 district, Kazakhstan'],route:['Маршрут в 2ГИС','2ГИС арқылы жол табу','Directions on 2GIS'],mapTitle:['Aspandiar на карте','Aspandiar картада','Aspandiar on the map'],openMap:['Открыть в 2ГИС','2ГИС-та ашу','Open in 2GIS'],footerLine:['С заботой о каждом госте.','Әр қонаққа қамқорлықпен.','With care for every guest.'],backToMenu:['К банкетному меню','Банкет мәзіріне','Back to banquet menus'],closePhoto:['Закрыть фото','Фотоны жабу','Close photo'],
illustration:['Пример подачи','Ұсыну үлгісі','Serving example'],referencePhoto:['Вариант по фото','Фото бойынша нұсқа','Photo reference'],realPhoto:['Фото сервировки','Дастархан фотосы','Table photo'],cold:['Закуски и ассорти','Тіскебасарлар мен ассорти','Appetisers & platters'],dessert:['Фрукты, сладости и чай','Жеміс, тәттілер және шай','Fruit, sweets & tea'],main:['Горячее','Ыстық тағамдар','Main courses'],chooseSalads:['Выберите салаты','Салаттарды таңдаңыз','Choose your salads'],chooseHot:['Выберите горячее','Ыстық тағамды таңдаңыз','Choose your main course'],choiceNote:['Предварительный выбор для обсуждения с администратором.','Әкімшімен талқылауға арналған алдын ала таңдау.','A preliminary selection to discuss with the team.'],selected:['выбрано','таңдалды','selected'],choiceLimit:['Сначала уберите один из выбранных салатов.','Алдымен таңдалған салаттардың бірін алып тастаңыз.','Remove a selected salad before choosing another.'],included:['Включено','Кіреді','Included'],bring:['С собой','Өзіңізбен','Bring your own'],notIncluded:['Не включено','Кірмейді','Not included'],oneChoice:['1 на выбор','1 түрі таңдауға','Choose 1'],saladTypes:['вида салатов','түрлі салат','salad varieties'],saladFixedNote:['Конкретные варианты салатов согласуйте с администрацией.','Нақты салат нұсқаларын әкімшілікпен келісіңіз.','Confirm individual salad options with the team.'],hotNotIncluded:['Горячее в этом меню не указано','Бұл мәзірде ыстық тағам көрсетілмеген','No main course is listed in this menu'],selectedMenu:['Выбрано меню','Таңдалған мәзір','Selected menu'],photoOpen:['Посмотреть фото','Фотоны көру','View photo'],tableCaption:['Состав и условия четырёх банкетных меню','Төрт банкет мәзірінің құрамы мен шарттары','Contents and arrangements for all four banquet menus'],compareRow:['Позиция','Тағам','Item'],
water:['Негазированная вода','Газдалмаған су','Still water'],drinks:['Безалкогольные и алкогольные напитки','Алкогольсіз және алкогольді сусындар','Soft drinks and alcoholic beverages'],besh:['Бешбармак','Бешбармақ','Beshbarmak'],tea:['Чай','Шай','Tea'],bread:['Хлебная корзина','Нан себеті','Bread basket'],fruit:['Фруктовое ассорти','Жеміс ассортиі','Fruit platter'],sweets:['Сладости к чаю','Шайға арналған тәттілер','Tea-time sweets'],oriental:['Восточные сладости','Шығыс тәттілері','Oriental sweets'],pastries:['Пирожные','Пирожныйлар','Cakes & pastries'],meat:['Мясное ассорти','Ет ассортиі','Meat platter'],chicken:['Куриное ассорти','Тауық ассортиі','Chicken platter'],fish:['Рыбное ассорти','Балық ассортиі','Fish platter'],rolls:['Рулетики из кабачков и баклажанов','Кәді мен баялды орамалары','Courgette & aubergine rolls'],samsaGeneral:['Самса','Самса','Samsa'],samsaChicken:['Самса с курицей','Тауық еті қосылған самса','Chicken samsa'],saladLine:['Салаты','Салаттар','Salads'],hotLine:['Горячее блюдо','Ыстық тағам','Main course'],unlimited:['Без ограничений','Шектеусіз','Unlimited'],
waHello:['Здравствуйте! Хочу обсудить банкет в Aspandiar.','Сәлеметсіз бе! Aspandiar-да банкет өткізуді талқылағым келеді.','Hello! I would like to discuss a banquet at Aspandiar.'],waMenu:['Меню','Мәзір','Menu'],waPer:['₸ на гостя','₸ бір қонаққа','₸ per guest'],waGuests:['Количество гостей','Қонақ саны','Number of guests'],waSalads:['Предпочтительные салаты','Таңдаған салаттар','Preferred salads'],waHot:['Горячее','Ыстық тағам','Main course'],waDate:['Подскажите свободные даты и условия бронирования.','Бос күндер мен брондау шарттарын айтыңызшы.','Please let me know available dates and booking arrangements.']
};
const packages=[
{price:5000,salads:2,hot:false,cold:['meat','chicken'],names:['Лёгкий стол','Жеңіл дастархан','Light table'],descriptions:['Ассорти, два вида салатов, фрукты, сладости и чай. Для событий со своим бешбармаком.','Ассорти, екі түрлі салат, жеміс, тәттілер және шай. Бешбармақты өзіңіз әкелесіз.','Platters, two salad varieties, fruit, sweets and tea. Bring your own beshbarmak.']},
{price:7000,salads:3,hot:true,cold:['meat','chicken'],names:['С горячим','Ыстық тағаммен','With a main'],descriptions:['Три вида салатов и одно горячее блюдо — к ассорти, фруктам, сладостям и чаю.','Ассорти, жеміс, тәттілер мен шайға қосымша үш түрлі салат және бір ыстық тағам.','Three salad varieties and one main course, alongside platters, fruit, sweets and tea.']},
{price:8000,salads:3,hot:true,cold:['meat','chicken','fish','samsa'],names:['Банкетный','Банкет дастарханы','Banquet table'],descriptions:['Мясное, куриное и рыбное ассорти, куриная самса, три салата на выбор и горячее.','Ет, тауық және балық ассортиі, тауық самсасы, таңдауға үш салат пен бір ыстық тағам.','Meat, chicken and fish platters, chicken samsa, three salads of your choice and a main course.']},
{price:10000,salads:3,hot:true,cold:['meat','chicken','fish','rolls','samsa'],names:['Полный стол','Толық дастархан','Full banquet'],descriptions:['Полный банкетный стол: ассорти, овощные рулетики, самса, три салата, бешбармак и горячее.','Толық банкет дастарханы: ассорти, көкөніс орамалары, самса, үш салат, бешбармақ және ыстық тағам.','A full banquet table: platters, vegetable rolls, samsa, three salads, beshbarmak and a main course.']}
];
const dishes={meat:{image:'meat-cold-platter.webp',kind:'illustration'},chicken:{image:'table-chicken.jpg',kind:'realPhoto'},fish:{image:'fish-cold-platter.webp',kind:'illustration'},samsa:{key:'samsaGeneral',image:'chicken-samsa.webp',kind:'illustration'},rolls:{image:'vegetable-rolls.webp',kind:'illustration'},fruit:{image:'table-fruit.jpg',kind:'realPhoto'},sweets:{image:'tea-sweets-cookies.webp',kind:'illustration'},oriental:{image:'oriental-sweets.webp',kind:'illustration'},pastries:{image:'table-pastries.jpg',kind:'realPhoto'},bread:{image:'table-bread.jpg',kind:'realPhoto'},tea:{image:'tea-porcelain.webp',kind:'illustration'},besh:{image:'beshbarmak.webp',kind:'illustration'}};
const saladOptions=[
{id:'eggplant',image:'eggplant-sesame.jpg',names:['Салат с баклажанами и кунжутом','Баялды мен күнжіт салаты','Aubergine & sesame salad']},
{id:'beet',image:'beet-pear.jpg',names:['Салат со свёклой, грушей и сыром','Қызылша, алмұрт және ірімшік салаты','Beetroot, pear & cheese salad']},
{id:'warm',image:'warm-vegetables.jpg',names:['Тёплый овощной салат','Жылы көкөніс салаты','Warm vegetable salad']},
{id:'classic',image:'classic-salad.jpg',names:['Праздничный салат','Мерекелік салат','Celebration salad']},
{id:'sheikh',image:'sheikh-salad.jpg',names:['Салат «Шейх»','«Шейх» салаты','Sheikh salad']},
{id:'cheese',image:'cheese-salad.jpg',names:['Овощной салат с сырными шариками','Ірімшік шарлары қосылған көкөніс салаты','Vegetable salad with cheese balls']},
{id:'pumpkin',image:'pumpkin-salad.jpg',names:['Салат с тыквой и цветной капустой','Асқабақ пен гүлді қырыққабат салаты','Pumpkin & cauliflower salad']},
{id:'pear',image:'pear-cheese.jpg',names:['Салат с грушей и сыром','Алмұрт пен ірімшік салаты','Pear & cheese salad']},
{id:'crispy',image:'crispy-eggplant.jpg',names:['Хрустящие баклажаны с томатами','Қызанақ қосылған қытырлақ баялды','Crispy aubergine & tomato salad']},
{id:'potato',image:'salad-potato.jpg',names:['Салат с картофелем пай','Картоп пай қосылған салат','Salad with crispy potato straws']},
{id:'pineapple',image:'pineapple-salad.jpg',names:['Салат с ананасом и яйцом','Ананас пен жұмыртқа салаты','Pineapple & egg salad']}
];
const hotOptions=[{id:'chicken-potatoes',image:'chicken-potatoes.jpg',names:['Курица с картофелем и овощами','Картоп пен көкөніс қосылған тауық','Chicken with potatoes & vegetables']},{id:'cutlet',image:'cutlet-mash.jpg',names:['Котлета с картофельным пюре','Картоп езбесімен котлет','Cutlet with mashed potatoes']},{id:'bread-pot',image:'bread-pot.jpg',names:['Горячее в хлебной чаше','Нан ыдысындағы ыстық тағам','Main course in a bread bowl']}];
const faq = [
[['Нужно ли приносить бешбармак?','Бешбармақты өзіміз әкелуіміз керек пе?','Should we bring beshbarmak?'],['В меню за 5 000, 7 000 и 8 000 ₸ бешбармак приносите с собой. В меню за 10 000 ₸ он включён. Количество, время доставки и подачу согласуйте с администрацией.','5 000, 7 000 және 8 000 ₸ мәзірлерінде бешбармақты өзіңіз әкелесіз. 10 000 ₸ мәзіріне бешбармақ кіреді. Мөлшерін, жеткізу уақытын және ұсынуын әкімшілікпен келісіңіз.','Bring your own beshbarmak for the 5,000, 7,000 and 8,000 ₸ menus. It is included in the 10,000 ₸ menu. Agree quantities, delivery timing and serving arrangements with the team.']],
[['Какие напитки нужно принести?','Қандай сусын әкелу керек?','Which drinks should we bring?'],['В меню за 5 000 и 7 000 ₸ указана негазированная вода с собой. В меню за 8 000 и 10 000 ₸ — безалкогольные и алкогольные напитки с собой. Чай без ограничений включён во все четыре меню. Остальные условия уточните перед банкетом.','5 000 және 7 000 ₸ мәзірлерінде газдалмаған суды өзіңіз әкелесіз. 8 000 және 10 000 ₸ мәзірлерінде алкогольсіз және алкогольді сусындарды өзіңіз әкелесіз. Шектеусіз шай төрт мәзірге де кіреді. Қалған шарттарды алдын ала нақтылаңыз.','The 5,000 and 7,000 ₸ menus list still water to bring yourself. The 8,000 and 10,000 ₸ menus list soft drinks and alcoholic beverages to bring yourself. Unlimited tea is included in all four menus. Confirm other arrangements before the event.']],
[['Можно ли выбрать салаты и горячее?','Салат пен ыстық тағамды таңдауға бола ма?','Can we choose salads and a main course?'],['В меню за 8 000 и 10 000 ₸ — три салата и одно горячее на выбор. За 7 000 ₸ — три вида салатов и одно горячее на выбор; за 5 000 ₸ — два вида салатов. Соберите предпочтения на сайте и подтвердите выбор с администратором.','8 000 және 10 000 ₸ мәзірлерінде таңдауға үш салат пен бір ыстық тағам бар. 7 000 ₸ мәзірінде үш түрлі салат және таңдауға бір ыстық тағам, 5 000 ₸ мәзірінде екі түрлі салат көрсетілген. Қалауыңызды сайтта таңдап, әкімшімен растаңыз.','The 8,000 and 10,000 ₸ menus include three salads and one main of your choice. The 7,000 ₸ menu lists three salad varieties and one main of your choice; the 5,000 ₸ menu lists two salad varieties. Make a preliminary selection here and confirm with the team.']],
[['Как забронировать дату?','Күнді қалай брондаймыз?','How do we book a date?'],['Напишите в WhatsApp или позвоните: +7 702 000 80 30. Сообщите дату, формат события, число гостей и меню. Администратор подтвердит свободную дату, итоговую стоимость и условия бронирования.','WhatsApp арқылы жазыңыз немесе +7 702 000 80 30 нөміріне қоңырау шалыңыз. Күнін, шара түрін, қонақ санын және мәзірді айтыңыз. Әкімші бос күнді, соңғы бағаны және брондау шарттарын растайды.','Message us on WhatsApp or call +7 702 000 80 30. Share your date, event type, guest count and menu. The team will confirm availability, final cost and booking arrangements.']],
[['Как уточнить состав и аллергены?','Құрамы мен аллергендерін қалай білеміз?','How can we check ingredients and allergens?'],['Сообщите администратору о пищевых ограничениях заранее. Точный состав, вес порций и возможные замены уточняются при согласовании банкетного меню.','Тамақтануға қатысты шектеулеріңізді әкімшіге алдын ала хабарлаңыз. Нақты құрамы, порция мөлшері мен ауыстыру мүмкіндігі мәзірді келіскенде нақтыланады.','Tell the team about dietary requirements in advance. Exact ingredients, portion sizes and substitutions are confirmed when agreeing your banquet menu.']]
];
const state={lang:'ru',price:8000,guests:50,salads:[],hot:null,filter:'all',comparison:false};
const langs=['ru','kk','en'];
try{const saved=localStorage.getItem('aspandiar-language');if(langs.includes(saved))state.lang=saved;}catch{}
const requestedLanguage=new URLSearchParams(location.search).get('lang');if(langs.includes(requestedLanguage))state.lang=requestedLanguage;
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),idx=()=>langs.indexOf(state.lang),t=k=>text[k][idx()],name=d=>d.names[idx()],pkg=()=>packages.find(p=>p.price===state.price),fmt=n=>new Intl.NumberFormat(state.lang==='kk'?'kk-KZ':state.lang==='en'?'en-US':'ru-RU').format(n),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function announce(s){$('#announcement').textContent=s;}
function whatsapp(menu=true){const lines=[t('waHello')];if(menu){lines.push(`${t('waMenu')}: ${fmt(state.price)} ${t('waPer')}.`,`${t('waGuests')}: ${state.guests}.`);if(state.salads.length)lines.push(`${t('waSalads')}: ${state.salads.map(id=>name(saladOptions.find(d=>d.id===id))).join(', ')}.`);if(pkg().hot&&state.hot)lines.push(`${t('waHot')}: ${name(hotOptions.find(d=>d.id===state.hot))}.`);}lines.push(t('waDate'));return 'https://wa.me/77020008030?text='+encodeURIComponent(lines.join('\n'));}
function updateEstimate(){$('#estimate-total').textContent=fmt(state.price*state.guests)+' ₸';$('#guest-count').value=state.guests;['#menu-whatsapp','#estimate-whatsapp','#mobile-whatsapp'].forEach(s=>$(s).href=whatsapp());$$('.whatsapp-general').forEach(a=>a.href=whatsapp(false));}
function photoButton(image,title,kind,css='dish-thumb'){return `<button class="${css}" data-photo="${esc(image)}" data-caption="${esc(title)} · ${esc(t(kind))}" aria-label="${esc(t('photoOpen')+': '+title)}"><img src="assets/${esc(image)}" alt="${esc(title)}" loading="lazy"></button>`;}
function dishCard(id){const d=dishes[id],title=id==='samsa'&&state.price===8000?t('samsaChicken'):t(d.key||id);return `<article class="included-dish">${photoButton(d.image,title,d.kind)}<div><h4>${title}</h4>${id==='tea'?`<p>${t('unlimited')}</p>`:''}<small class="source-label ${d.kind==='illustration'?'illustration':''}">${t(d.kind)}</small></div></article>`;}
function renderTabs(){$('.package-tabs').innerHTML=packages.map(p=>`<button id="tab-${p.price}" role="tab" aria-selected="${p.price===state.price}" aria-controls="menu-panel" tabindex="${p.price===state.price?0:-1}" data-price="${p.price}" class="${p.price===state.price?'active':''}"><span>${fmt(p.price)} <i>₸</i></span><small>${name(p)}</small></button>`).join('');$('#menu-panel').setAttribute('aria-labelledby','tab-'+state.price);}
function renderMenu(){const p=pkg();$('#menu-price').textContent=fmt(p.price);$('#menu-description').textContent=p.descriptions[idx()];const bring=p.price<=7000?['water','besh']:p.price===8000?['drinks','besh']:['drinks'];$('#bring-list').innerHTML=bring.map(k=>`<li>${t(k)}</li>`).join('');$('#original-menu').href=`assets/menu-${p.price}.png`;const dessert=['fruit','sweets','oriental','pastries','bread','tea'];$('#included-groups').innerHTML=`<div class="included-group"><h3>${t('cold')}</h3><div class="included-grid">${p.cold.map(dishCard).join('')}</div></div>${p.price===10000?`<div class="included-group"><h3>${t('main')}</h3><div class="included-grid">${dishCard('besh')}</div></div>`:''}<div class="included-group"><h3>${t('dessert')}</h3><div class="included-grid">${dessert.map(dishCard).join('')}</div></div>`;$('#included-count').textContent=(p.cold.length+dessert.length+1+(p.hot?1:0)+(p.price===10000?1:0))+' '+t('positions');renderSelections();updateEstimate();}
function selectionCard(d,category){const selected=category==='salads'?state.salads.includes(d.id):state.hot===d.id;return `<button class="choice-card ${selected?'chosen':''}" data-choice="${category}" data-id="${d.id}" aria-pressed="${selected}"><div class="choice-image"><img src="assets/${d.image}" alt="${esc(name(d))}" loading="lazy"><span class="choice-check" aria-hidden="true">${selected?'✓':'+'}</span></div><span class="choice-name">${esc(name(d))}</span><small>${t('referencePhoto')}</small></button>`;}
function renderSelections(){const p=pkg();$('#selection-block').innerHTML=`<div class="selection-group"><div class="selection-heading"><h3>${t('chooseSalads')}</h3><span class="selection-count">${state.salads.length}/${p.salads} ${t('selected')}</span></div><p class="choice-note">${t('choiceNote')}${p.price<=7000?' '+t('saladFixedNote'):''}</p><div class="choice-grid salads-grid">${saladOptions.map(d=>selectionCard(d,'salads')).join('')}</div></div>${p.hot?`<div class="selection-group"><div class="selection-heading"><h3>${t('chooseHot')}</h3><span class="selection-count">${state.hot?'1':'0'}/1 ${t('selected')}</span></div><p class="choice-note">${t('choiceNote')}</p><div class="choice-grid">${hotOptions.map(d=>selectionCard(d,'hot')).join('')}</div></div>`:`<p class="no-main">${t('hotNotIncluded')}</p>`}`;}
function renderComparison(){const rows=[['meat','yes'],['chicken','yes'],['fish','fish'],['rolls','rolls'],['samsaGeneral','samsa'],['saladLine','salad'],['hotLine','hot'],['besh','besh'],['fruit','yes'],['sweets','yes'],['oriental','yes'],['pastries','yes'],['bread','yes'],['tea','tea'],['water','water'],['drinks','drinks']];const value=(type,p)=>{if(type==='yes')return t('included');if(['fish','rolls','samsa'].includes(type))return p.cold.includes(type)?t('included'):'—';if(type==='salad')return `${p.salads} ${t('saladTypes')}`;if(type==='hot')return p.hot?t('oneChoice'):t('notIncluded');if(type==='besh')return p.price===10000?t('included'):t('bring');if(type==='tea')return t('unlimited');if(type==='water')return p.price<=7000?t('bring'):'—';return p.price>=8000?t('bring'):'—';};$('#comparison').innerHTML=`<div class="table-scroll" tabindex="0" role="region" aria-label="${t('tableCaption')}"><table><caption class="sr-only">${t('tableCaption')}</caption><thead><tr><th scope="col">${t('compareRow')}</th>${packages.map(p=>`<th scope="col" class="${p.price===state.price?'current':''}">${fmt(p.price)} ₸</th>`).join('')}</tr></thead><tbody>${rows.map(([label,type])=>`<tr><th scope="row">${t(label)}</th>${packages.map(p=>`<td class="${p.price===state.price?'current':''}">${value(type,p)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;$('#comparison').hidden=!state.comparison;$('#compare-button').textContent=state.comparison?t('hideCompare'):t('compareMenus');$('#compare-button').setAttribute('aria-expanded',String(state.comparison));}
function renderGallery(){const all=[...saladOptions.map(d=>({...d,category:'salads'})),...hotOptions.map(d=>({...d,category:'hot'}))];$('#dish-gallery').innerHTML=all.filter(d=>state.filter==='all'||d.category===state.filter).map(d=>`<article class="gallery-card">${photoButton(d.image,name(d),'referencePhoto','gallery-photo')}<div><span>${t(d.category==='salads'?'salads':'hotDishes')}</span><h3>${esc(name(d))}</h3></div></article>`).join('');$$('[data-filter]').forEach(b=>{b.classList.toggle('selected',b.dataset.filter===state.filter);b.setAttribute('aria-pressed',String(b.dataset.filter===state.filter));});}
function renderFaq(){const opened=[...$$('#faq-list details[open]')].map(d=>Number(d.dataset.index));$('#faq-list').innerHTML=faq.map(([q,a],i)=>`<details data-index="${i}" ${opened.includes(i)?'open':''}><summary>${esc(q[idx()])}<span aria-hidden="true">+</span></summary><p>${esc(a[idx()])}</p></details>`).join('');}
function translate(){document.documentElement.lang=state.lang;document.title=['Aspandiar — Банкетный ресторан в Атырау','Aspandiar — Атыраудағы банкет мейрамханасы','Aspandiar — Banquet Restaurant in Atyrau'][idx()];$$('[data-t]').forEach(el=>el.innerHTML=t(el.dataset.t));$$('[data-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.aria)));$$('[data-alt]').forEach(el=>el.alt=t(el.dataset.alt));$$('[data-title]').forEach(el=>el.title=t(el.dataset.title));$$('[data-lang]').forEach(el=>{el.classList.toggle('selected',el.dataset.lang===state.lang);el.setAttribute('aria-pressed',String(el.dataset.lang===state.lang));});renderTabs();renderMenu();renderComparison();renderGallery();renderFaq();}
function setMenu(price){const p=packages.find(x=>x.price===Number(price));if(!p)throw new Error('Invalid menu price');state.price=p.price;state.salads=state.salads.slice(0,p.salads);if(!p.hot)state.hot=null;renderTabs();renderMenu();renderComparison();announce(t('selectedMenu')+': '+fmt(state.price)+' ₸');}
function setGuests(guests){if(!Number.isFinite(Number(guests)))return;state.guests=Math.min(200,Math.max(1,Math.round(Number(guests))));updateEstimate();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.lang){state.lang=b.dataset.lang;try{localStorage.setItem('aspandiar-language',state.lang);}catch{}translate();}else if(b.dataset.price){setMenu(b.dataset.price);$('#tab-'+state.price).focus();}else if(b.dataset.choice){const id=b.dataset.id;if(b.dataset.choice==='salads'){if(state.salads.includes(id))state.salads=state.salads.filter(x=>x!==id);else if(state.salads.length<pkg().salads)state.salads.push(id);else{announce(t('choiceLimit'));const group=b.closest('.selection-group');let notice=group.querySelector('.selection-notice');if(!notice){notice=document.createElement('p');notice.className='selection-notice';notice.setAttribute('role','status');group.querySelector('.selection-heading').after(notice);}notice.textContent=t('choiceLimit');return;}}else state.hot=state.hot===id?null:id;renderSelections();const updated=$(`[data-id="${id}"]`);if(updated)updated.focus({preventScroll:true});updateEstimate();}else if(b.dataset.filter){state.filter=b.dataset.filter;renderGallery();}else if(b.dataset.photo){$('#dialog-image').src='assets/'+b.dataset.photo;$('#dialog-image').alt=b.dataset.caption;$('#dialog-caption').textContent=b.dataset.caption;$('#photo-dialog').showModal();}});
$('.package-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=packages.findIndex(p=>p.price===state.price);i=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4;setMenu(packages[i].price);$('#tab-'+state.price).focus();});
$('#compare-button').addEventListener('click',()=>{state.comparison=!state.comparison;renderComparison();});$('#guest-count').addEventListener('change',e=>setGuests(e.target.value));$('#guest-count').addEventListener('input',e=>{const n=Number(e.target.value);if(n>=1&&n<=200){state.guests=Math.round(n);updateEstimate();}});$('#guest-minus').addEventListener('click',()=>setGuests(state.guests-10));$('#guest-plus').addEventListener('click',()=>setGuests(state.guests+10));$('.dialog-close').addEventListener('click',()=>$('#photo-dialog').close());$('#photo-dialog').addEventListener('click',e=>{if(e.target===$('#photo-dialog'))$('#photo-dialog').close();});
translate();
// Supporting browsers can configure the same visible menu controls.
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();const read=()=>({language:state.lang,pricePerPerson:state.price,guests:state.guests,estimatedMenuCost:state.price*state.guests,selectedSalads:[...state.salads],selectedHotDish:state.hot,whatsappDraftUrl:whatsapp()});const toolList=[{name:'get_banquet_selection',title:'Read banquet selection',description:'Read the current menu, guest count, preferences and estimated menu cost.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:read},{name:'configure_banquet',title:'Configure banquet menu',description:'Select a menu and guest count on this page. Prepares a selection and WhatsApp draft; does not send a message or book an event.',inputSchema:{type:'object',properties:{pricePerPerson:{type:'integer',enum:[5000,7000,8000,10000]},guests:{type:'integer',minimum:1,maximum:200},language:{type:'string',enum:langs}},required:['pricePerPerson','guests'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['pricePerPerson','guests','language'].includes(k))||!packages.some(p=>p.price===input.pricePerPerson)||!Number.isInteger(input.guests)||input.guests<1||input.guests>200||(input.language&&!langs.includes(input.language)))throw new Error('Invalid banquet configuration');if(input.language)state.lang=input.language;setMenu(input.pricePerPerson);setGuests(input.guests);translate();return read();}}];for(const tool of toolList){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
